### ISSUE TITLE
Make it easier to add servers

### ISSUE THREAD

**Issue by Faunsce** [xornet-cloud/Xornet#154]
Clicking a(n)f (unassigned) server will store its uuid (if its linked to your account) and instantly open a window of which datacenters to add it to

and or 

simply copy the uuid of any server you click on the uuid section of to clipboard to just make it slightly easier to add a server to a datacenter

**Comment by Faunsce** [comment]
I will go ahead and tackle this one as well, securing things for me to get done, if it seems itll take too long and is key, i am however willing to hand it off. but im confident this will be done asap

**Comment by Geoxor** [comment]
also make it so the reporter logs its UUID on the console if possible so u can easily copy it from there just to give people many ways of adding their computers for ease

**Comment by Geoxor** [comment]
you may have noticed the little "primary" badge on the DCs now, the idea is that your machine will be auto added in the primary datacenter

**Comment by Faunsce** [comment]
> 
> 
> also make it so the reporter logs its UUID on the console if possible so u can easily copy it from there just to give people many ways of adding their computers for ease

@Geoxor Is that not what the add link already does? I was certain that the end of the url was the machines uuid

**Comment by Geoxor** [comment]
no i meant reply it over and over while its running cus after you link it u restart it and then u cant see the UUID anymore
