### ISSUE TITLE
Use SHA-256 to encrypt software versions and other details about machines so users feel secure

### ISSUE THREAD

**Issue by Geoxor** [xornet-cloud/Xornet#155]

**Comment by xE0F9** [comment]
i'll feel secure

**Comment by xE0F9** [comment]
This is my idea:
On login: Browser saves a key generated from password to sessionData.
Machine: Stores an encryption key for that password and encrypts it's data before sending it to the server.
Server: Hosts that data and gives it encrypted to the user's Browser who decrypts it with the key it has

**Comment by Geoxor** [comment]
Heres @CelluloidRacer2's idea

![image](https://user-images.githubusercontent.com/34042825/123146089-3112cb00-d466-11eb-9326-a8a49b26833b.png)

**Comment by CelluloidRacer2** [comment]
The KDF function is one that uses iterations in this design, like PBKDF2. Bcrypt is an alternative, it just needs to be more difficult to bruteforce since clients have to download the crypted key to derive the master key

**Comment by Geoxor** [comment]
This should be addressed in the future

**Comment by CelluloidRacer2** [comment]
Perhaps we should open this issue with low priority? If not, that's cool too. I think it would be good to keep this in mind for processing/storing machine secrets if we get to that point

**Comment by xE0F9** [comment]
Yes, I personally don't feel safe having stuff like my MAC Address or software versions of my server out there

**Comment by Faunsce** [comment]
Low priority is definetly a good idea, makes sure its something to be done but that its not exactly top of the list
