### ISSUE TITLE
Back button seems redundant

### ISSUE THREAD

**Issue by Faunsce** [xornet-cloud/Xornet#191]
So the back button on the site seems a bit redundant to me? Usually the user will just, use their browsers back button.
especially since thumb mouse buttons tend to be auto maped to forward and back so obviously using the browser ones seems to be industry standard. I also can't rly think of any instances of other sites have such button. Anyways welcome to show examples.

**Comment by Geoxor** [comment]
do you see a back button on the PWA?
![image](https://user-images.githubusercontent.com/34042825/124347081-2cc77a00-dbeb-11eb-9506-622ace05e2b8.png)

plus its common to have a back button at the top right for mobile users, some people use gestures and they dont have a back button
